[package]
name = "newsletter"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
actix-web = "4.9.0"
config = "0.14.0"
diesel = { version = "2.2.3", features = ["postgres"] }
reqwest = "0.12.7"
serde = { version = "1.0.209", features = ["derive"] }
tokio = "1.39.3"
