application_port: 8000

application:
  port: 8000
  hmac_secret: "psssst-secret-alalal-lllaaj-1234-aaahjajla-113r1nnha-adgagagljhakgagajkhagalh"

database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"

email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
  timeout: 3

redis_uri: "redis://127.0.0.1:6379"
